services:
  db_test:
    image: postgres:14
    container_name: postgres_test
    env_file:
      - .env.test.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api_test:
    build:
      context: .
      target: development
    container_name: hih_api_test
    command: tail -f /dev/null 
    environment:
      - PORT=${PORT}
      - NODE_ENV=test
    env_file:
      - .env.test.local
    depends_on:
      db_test:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules